<a href="https://colab.research.google.com/github/gabin0918/Test/blob/main/algebraLiniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Mnozenie macierzy

In [3]:
X=np.array([[5,3],[3,9]])
print(X)

[[5 3]
 [3 9]]


In [5]:
Y=np.array([[1],[-1]])
print(Y)

[[ 1]
 [-1]]


In [7]:
Z=X.dot(Y)
print(Z)

[[ 2]
 [-6]]


In [9]:
X=np.array([[2,-1,3],[3,1,0]])
Y=np.array([[2,1,-1],[0,-1,2],[3,2,0]])
Z=X.dot(Y)
print(Z)

[[13  9 -4]
 [ 6  2 -1]]


In [11]:
#wyznacznik macierzy
A=np.array([[2,4],[-1,3]])
round(np.linalg.det(A))

10

In [12]:
#Ślad macierzy
np.trace(A)

5

In [22]:
#macierz jednostkowa
A=np.eye(5,dtype='int')
print(A)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [25]:
A=np.array([[2,-1],[4,3]])

In [26]:
#macierz odwrotna
B=np.linalg.inv(A)
print(B)

[[ 0.3  0.1]
 [-0.4  0.2]]


In [29]:
np.set_printoptions(precision=4,suppress=True)
np.dot(A,B)

array([[ 1., -0.],
       [ 0.,  1.]])

In [30]:
#macierz transponowana
np.transpose(A)


array([[ 2,  4],
       [-1,  3]])

In [32]:
A.T

array([[ 2,  4],
       [-1,  3]])

#uklady rownan

In [39]:
A=np.array([[2,4],[1,-1]])
B=np.array([[10],[-1]])
print(A,'\n\n',B)

[[ 2  4]
 [ 1 -1]] 

 [[10]
 [-1]]


In [37]:
A_inv=np.linalg.inv(A)
X=A_inv.dot(B)
print(X)

[[1.]
 [2.]]


In [40]:
X.shape

(2, 1)