In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
!git config --global user.name "gabin0918"

In [ ]:
!git clone https://github.com/gabin0918/DataScienceBootcamp.git

Cloning into 'DataScienceBootcamp'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), 5.35 KiB | 5.35 MiB/s, done.
Resolving deltas: 100% (3/3), done.


In [ ]:
%cd DataScienceBootcamp

/content/DataScienceBootcamp


In [ ]:
print("test")

test


In [ ]:
!git add Boot.ipynb

fatal: pathspec 'Boot.ipynb' did not match any files


In [ ]:
!ls /content/gdrive/MyDrive/
# Kopiowanie pliku do katalogu repozytorium
!cp /content/gdrive/MyDrive/'Colab Notebooks'/Boot.ipynb /content/DataScienceBootcamp/




 apostazja_dlugi.rtf.gdoc  'Folder bez nazwy'		'ść-fiz (1).gdoc'   udemy
 Classroom		   'Formularz bez nazwy.gform'	 ść-fiz.gdoc	    Untitled0.ipynb
'Colab Notebooks'	    loginy_klasy1.gdoc		 Takeout	    Zadanie


# Dodaj zmiany

In [ ]:
!git add Boot.ipynb

!git commit -m "Aktualizacja notatnika"

!git push origin main

[main 4151a7d] Aktualizacja notatnika
 1 file changed, 1 insertion(+)
 create mode 100644 Boot.ipynb
fatal: could not read Username for 'https://github.com': No such device or address


In [ ]:
import getpass

token = getpass.getpass('Podaj swój GitHub token: ')
repo_url = f'https://{token}@github.com/gabin0918/DataScienceBootcamp.git'

!git remote set-url origin {repo_url}


Podaj swój GitHub token: ··········


In [ ]:
!git push origin main

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.60 KiB | 1.60 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/gabin0918/DataScienceBootcamp.git
   38803a5..4151a7d  main -> main


In [ ]:
!git add Boot.ipynb
!git commit -m "Test2"
!git push origin main

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date


In [ ]:
import numpy as np

In [ ]:
A=np.random.randn(5)

In [ ]:
A



array([-1.29527097,  0.85840649,  1.42395484, -0.56368897, -0.42456258])

In [ ]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

# generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand()

0.1965823616800535

In [ ]:
np.random.randint(10)

0

In [ ]:
np.random.randint(low=10,high=101,size=10)

array([10, 60, 46, 44, 58, 13, 52, 87, 31, 83])

In [ ]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [ ]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer t

In [ ]:
np.random.choice([4,2,1,3,5])

4

In [ ]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)

In [ ]:
data

array([0, 5, 8, 4, 6, 1, 9, 3, 7, 2])

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(10)

22026.465794806718

In [ ]:
np.sqrt(9)

3.0

In [ ]:
np.all([2,3,4])

True

In [ ]:
np.all([0,1,1])

False

In [ ]:
np.any([0,1])

True

In [ ]:
bool(0)

False

In [ ]:
A=np.random.randn(5)

In [ ]:
A


array([ 0.3869025 ,  0.33053441, -1.43582841,  0.02752832,  1.12060466])

In [ ]:
np.argmax(A)

4

In [ ]:
A[np.argmax(A)]

1.120604656809467

In [ ]:
np.argmin(A)

2

In [ ]:
np.argsort(A)

array([2, 3, 1, 0, 4])

In [ ]:
np.min(A)

-1.4358284060465922

In [ ]:
np.max(A)

1.120604656809467

In [ ]:
np.mean(A)

0.08594829427681742

In [ ]:
np.median(A)

0.3305344056385035

In [ ]:
np.std(A)

0.8414424289791992

# indeksowanie

In [ ]:
A = np.arange(20)
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x=np.argmax(A)
A[x]

19

In [ ]:
A[2:
  ]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[[0,2]]

array([0, 2])

In [ ]:
A[-1]

19

In [ ]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[:,3]

array([ 3,  8, 13, 18])

In [ ]:
A[0,2]

2

In [ ]:
A[-1]

array([15, 16, 17, 18, 19])

In [ ]:
A[1,1]

6

In [ ]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1,2]=14

In [ ]:
A


array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# iteracja po tablicach itp

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A: print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A: print(row[0])

0
5
10
15


In [ ]:
for row in A: print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat: print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
A = np.arange(start=-10,stop=10,step=0.5)

In [ ]:
A



array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [ ]:
A=A.reshape(10,-1)

In [ ]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
np.bitwise_and(A>-5,A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A>-5,A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A<-5,A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[np.bitwise_or(A<-5,A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [ ]:
!git add .

In [ ]:
!git commit

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [ ]:
!pwd


/content/DataScienceBootcamp


In [ ]:
!ls


Boot.ipynb


In [ ]:
%cd /content/DataScienceBootcamp/

/content/DataScienceBootcamp


In [ ]:
!git diff

In [ ]:
!git commit

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [ ]:
!git ls-files


.gitignore
Boot.ipynb


In [ ]:
!git add Boot.ipynb

!git commit -m "Aktualizacja notatnika"

!git push origin main

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date


In [ ]:
!git config --list

filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=gabin0918
user.email=gabin0918@gmail.com
user.password=S2afir1234
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://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@github.com/gabin0918/DataScienceBootcamp.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main


In [ ]:
!git config --global --unset user.password

In [ ]:
!ls /content


DataScienceBootcamp  gdrive  sample_data


In [ ]:
%cd DataScienceBootcamp
!git add Boot.ipynb

!git commit -m "Aktualizacja notatnika"

!git push origin main

[Errno 2] No such file or directory: 'DataScienceBootcamp'
/content/DataScienceBootcamp
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Everything up-to-date


In [ ]:
!git clone https://github.com/gabin0918/DataScienceBootcamp.git


Cloning into 'DataScienceBootcamp'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 3), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 6.92 KiB | 6.92 MiB/s, done.
Resolving deltas: 100% (3/3), done.


In [170]:
%cd DataScienceBootcamp


/content/DataScienceBootcamp/DataScienceBootcamp


In [171]:
!git add .


In [172]:
!git commit -m "proboje to zaktualizowac"


On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [173]:
!git clone https://github.com/gabin0918/DataScienceBootcamp.git


Cloning into 'DataScienceBootcamp'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 3), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 6.92 KiB | 6.92 MiB/s, done.
Resolving deltas: 100% (3/3), done.


In [175]:
%cd /content
!rm -rf DataScienceBootcamp

/content


In [176]:
!git clone https://github.com/gabin0918/DataScienceBootcamp.git


Cloning into 'DataScienceBootcamp'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 3), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 6.92 KiB | 6.92 MiB/s, done.
Resolving deltas: 100% (3/3), done.


In [177]:
!ls -R DataScienceBootcamp


DataScienceBootcamp:
Boot.ipynb


In [178]:
%cd DataScienceBootcamp


/content/DataScienceBootcamp


In [179]:
!ls


Boot.ipynb


In [180]:
!git add .


In [181]:
!git commit -m "Dopisany kod do pliku skryptu"


On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [182]:
!ls /content/gdrive/MyDrive/
# Kopiowanie pliku do katalogu repozytorium
!cp /content/gdrive/MyDrive/'Colab Notebooks'/Boot.ipynb /content/DataScienceBootcamp/




 apostazja_dlugi.rtf.gdoc  'Folder bez nazwy'		'ść-fiz (1).gdoc'   udemy
 Classroom		   'Formularz bez nazwy.gform'	 ść-fiz.gdoc	    Untitled0.ipynb
'Colab Notebooks'	    loginy_klasy1.gdoc		 Takeout	    Zadanie


In [183]:
!git add .


In [184]:
!git commit -m "Dopisany kod do pliku skryptu"

[main c798599] Dopisany kod do pliku skryptu
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite Boot.ipynb (92%)


In [186]:
!git config --global user.name gabin0918
!git push origin main

fatal: could not read Username for 'https://github.com': No such device or address


In [187]:
!git remote set-url origin https://<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>@github.com/gabin0918/DataScienceBootcamp.git


/bin/bash: line 1: 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: No such file or directory
