<a href="https://colab.research.google.com/github/gabin0918/Test/blob/main/numpy/funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
price=np.array([[12.4,12.8,11.9,12.6,1000],
               [12.5,13.0,11.7,12.2,2000],
               [12.2,13.4,12.2,13.2,1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [4]:
price.sum()

4650.1

In [9]:
price.sum(axis=0)#axis= 0 kolumny a 1 to wiersze

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [15]:
np.argmin(price,axis=0)

array([2, 0, 1, 1, 0])

In [16]:
np.max(price,axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [17]:
np.median(price)

12.6

In [22]:
np.set_printoptions(precision=4)

In [23]:
np.mean(price,axis=0)

array([  12.3667,   13.0667,   11.9333,   12.6667, 1500.    ])

In [24]:
np.std(price,axis=0)


array([1.2472e-01, 2.4944e-01, 2.0548e-01, 4.1096e-01, 4.0825e+02])

In [25]:
np.var(price,axis=0)

array([1.5556e-02, 6.2222e-02, 4.2222e-02, 1.6889e-01, 1.6667e+05])