<a href="https://colab.research.google.com/github/gabin0918/Test/blob/main/numpy/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

In [ ]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__annotations__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

# 1D array

In [ ]:
x= np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x= np.array([1.3,2.3,4.5])

In [ ]:
print(np.array([1.3,2.3,4.5]))

[1.3 2.3 4.5]


In [ ]:
x.dtype

dtype('float64')

# 2d array

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
print(x)

[[1 2]
 [3 4]]


In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x= np.array([[[4,3,5],[1,2,3]],[[1,2,3],[7,8,9]],[[7,5,8],[6,7,9]]])

In [ ]:
print(x)

[[[4 3 5]
  [1 2 3]]

 [[1 2 3]
  [7 8 9]]

 [[7 5 8]
  [6 7 9]]]


In [ ]:
x.shape

(3, 2, 3)

In [ ]:
x.ndim

3

# typy danych

In [ ]:
A=np.array([1,2,3],dtype='float')

In [ ]:
A.dtype

dtype('float64')

In [ ]:
A=np.array([1.4,2.6,5.7],dtype='int')

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 5])

In [ ]:
# tak jak na filmie juz sie nie da, trzeba tak przypisywac typy numpy
A=np.array([24,120,230]).astype('uint8')

In [ ]:
A.dtype

dtype('uint8')

# tworzenie tablic

In [ ]:
x =np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
array = np.zeros((4, 10), dtype='complex128', order='C')

In [ ]:
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3,3),fill_value=5,dtype=int)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5,stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=100,stop=10,step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0,stop=1,num=41)

array([0.   , 0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ,
       0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  , 0.425,
       0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  , 0.625, 0.65 ,
       0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  , 0.825, 0.85 , 0.875,
       0.9  , 0.925, 0.95 , 0.975, 1.   ])

In [ ]:
A=np.arange(15)

In [ ]:
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Podstawowe operacje na tablicach

In [ ]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A+3

array([6, 4, 7, 5])

In [ ]:
A*2

array([6, 2, 8, 4])

In [ ]:
A+3*B

array([12, -2, 13,  8])

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
np.amax(A)

4

In [ ]:
X=np.array([[1,2],[4,5]])
Y=np.array([[3,5],[3,4]])

In [ ]:
print(X,'\n')
print(Y)


[[1 2]
 [4 5]] 

[[3 5]
 [3 4]]


In [ ]:
#mnozenie maciezowe
np.dot(X,Y)

array([[ 9, 13],
       [27, 40]])

In [ ]:
#zwykle mnoz,porowanie
X*Y

array([[ 3, 10],
       [12, 20]])

In [ ]:
X.dot(Y)

array([[ 9, 13],
       [27, 40]])

In [ ]:
Y.dot(X)

array([[23, 31],
       [19, 26]])

In [ ]:
#to tez mnozenie maciezowe
X @Y

array([[ 9, 13],
       [27, 40]])

# generowanie liczb pseudolosowych

In [ ]:
#ustawiam ziarno
np.random.seed(0)

In [ ]:
# losowy rozklad normalny
np.random.randn()

1.764052345967664

In [ ]:
np.random.randn(10)

array([-1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ,
       -1.25279536,  0.77749036, -1.61389785, -0.21274028, -0.89546656])

In [ ]:
np.random.randn(10,4)

array([[ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297]])

In [ ]:
#losowa liczna z przedzialu 0-1
np.random.rand()

0.1965823616800535

In [ ]:
np.random.rand(10,2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [ ]:
#liczba calkowita do podanej
np.random.randint(10)

2

In [ ]:
np.random.randint(low=10,high=101)

37

In [ ]:
np.random.randint(low=10,high=101,size=10)

array([24, 51, 68, 75, 46, 20, 96, 53, 21, 12])

In [ ]:
#wybiera losowo element z listy(obiektu iterowalnego)
print(np.random.choice([1,2,5,7,8,9,0]))
np.random.choice(['python','java','sql'])

1


'sql'

In [ ]:
data=np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#uwaga zmienia dane bez przypisania
np.random.shuffle(data)

# Podstawowe funkcje

In [ ]:
# tj e do podanej potędi
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

3.0

In [ ]:
#jesli wszystkie sa prawdziwe to prawda
np.all([1,2,0])

False

In [ ]:
#jesli jakikolwiek prawdziwy to super
np.any([0,3,4])

True

In [ ]:
A=np.random.rand(5)
A

array([0.70373728, 0.28847644, 0.43328806, 0.75610669, 0.39609828])

In [ ]:
A.argmax() # dla indeksu

3


In [ ]:
A[np.argmax(A)] # dla wartosci

0.7561066938650409

In [ ]:
A.argmin()

1

In [ ]:
A[np.argmin(A)]

0.28847643704852866

In [ ]:
A.argsort()

array([1, 4, 2, 0, 3])

In [ ]:
A.max()

0.7561066938650409

In [ ]:
A.min()

0.28847643704852866

In [ ]:
A.mean()

0.5155413495217784

In [ ]:
np.median(A)

0.43328806198204406

In [ ]:
np.std(A)#odchylenie standARDOWE

0.18214286624402554

#indeksowanie wycinanie

In [ ]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A[2:8]

array([2, 3, 4, 5, 6, 7])

In [ ]:
A[2]

2

In [ ]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [ ]:
A[:2]

array([0, 1])

In [ ]:
A[-1]

19

In [ ]:
A[10:15]

array([10, 11, 12, 13, 14])

In [ ]:
A=A.reshape(4,-1)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[1]

array([5, 6, 7, 8, 9])

In [ ]:
A[:,-1]

array([ 4,  9, 14, 19])

In [ ]:
A[1,2]

7

In [ ]:
A[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [ ]:
A[1,2]=14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
  print(row[0])

0
5
10
15


In [ ]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
print(A)

[[ 0  1  2  3  4]
 [ 5  6 14  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
A.T #transponowanie

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

#maski logiczne

In [ ]:
A=np.arange(start=-10,stop=10,step=0.5)

In [ ]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [ ]:
A= A.reshape(10,-1)

In [ ]:
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A>-5,A<5
               )

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A>-5,A<5
               )]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])